font_family      mononoki 
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 20.0

background_opacity 1.0

#to allow setting of background opacity from terminal

allow_remote_control yes
dynamic_background_opacity yes
dynamic_background_color yes




##no warning when closing##
confirm_os_window_close 0

## window spacing##
window_padding_width 15

background #1A1816
foreground #C8B8A0
selection_background #3A332C
selection_foreground #D8C8B0
cursor #A88A5B
cursor_text_color #1A1816

color0  #1A1816
color1  #7B4A3E
color2  #6E7F5A
color3  #A88A5B
color4  #5B6258
color5  #715D58
color6  #66756A
color7  #C8B8A0

color8  #55514C
color9  #8A5748
color10 #879376
color11 #B79B6B
color12 #6A7267
color13 #85706A
color14 #7A8A7C
color15 #DDD0BD
