[main]
font = CloisterBlack:size=18
prompt = "♱ "
#icon-theme = Papirus-Dark
terminal = kitty
fuzzy = yes
horizontal-pad = 20
vertical-pad = 15
inner-pad = 5
width = 50

[border]
width = 4
radius = 0

[colors]
background = 181c27ff
border = ada37aff
selection = 172539ff
text = ada37aff


#dpi-aware=no
#icon-theme=Papirus-Dark
#width=25
#font=Hack:weight=bold:size=36
#line-height=50
#fields=name,generic,comment,categories,filename,keywords
#terminal=foot -e
#prompt="❯   " 
#layer=overlay
#[colors]
#background=282a36fa
#selection=3d4474fa
#border=fffffffa

#[border]
#radius=20

#[dmenu]
#exit-immediately-if-empty=yes

